apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 24h
  url: https://cowboysysop.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  dependsOn:
  - name: metrics-server
    namespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: "7.x"
      sourceRef:
        kind: HelmRepository
        name: vertical-pod-autoscaler
        namespace: kube-system
      interval: 12h
